<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQeI320z\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQeI320z/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerQeI320z.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerQeI320z\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerQeI320z\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'QeI320z',
    'container.build_id' => '50249807',
    'container.build_time' => 1540837438,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerQeI320z');
